name: bbob_dart
description: A port of the bbcode parser and trasnformer [bbob](https://github.com/JiLiZART/bbob) in dart.
version: 0.1.0
homepage: https://github.com/edwardez/bbob_dart
author: Edward Zhang <bangumin@protonmail.com>

environment:
  sdk: '>=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  path: ^1.3.1
  pedantic: ^1.0.0
  quiver: ^2.0.2
  test: ^1.0.0
